export const theme = {
  // Generated by https://colors.eva.design/
  colors: {
    primary: "#527DFC",
    secondary: "#68B3FF",
    //   white;
    //   black;
    //   grey0;
    //   grey1;
    //   grey2;
    //   grey3;
    //   grey4;
    //   grey5;
    //   greyOutline;
    //   searchBg;
    success: "#3EBA30",
    error: "#FF492D",
    warning: "#FFEE3D",
    //   divider;
    //   platform: {
    //     ios: {
    //       primary;
    //       secondary;
    //       grey;
    //       searchBg;
    //       success;
    //       error;
    //       warning;
    //     };
    //     android: {
    //       // Same as ios
    //     };
    //     web: {
    //       // Same as ios
    //     };
    //   };
  },
};
